<?php
/**
 * Created by PhpStorm.
 * User: anhnc
 * Date: 12/01/2017
 * Time: 08:19
 */

namespace Magestore\Multivendor\Block;


class Link extends \Magento\Framework\View\Element\Html\Link
{
    protected $_configHelper;
    public function __construct(
        \Magento\Framework\View\Element\Template\Context $context,
        \Magestore\Multivendor\Helper\Config $configHelper,
        array $data = [])
    {
        $this->_configHelper = $configHelper;
        parent::__construct($context, $data);
    }

    public function getHref()
    {
        return $this->_storeManager->getStore()->getUrl('multivendor/vendor/index');
    }
    public function  toHtml()
    {
        if($this->_configHelper->getStoreConfig('multivendor/general/enable_toplink') == 0){
            return '';
        }
        else{
            return parent::toHtml(); // TODO: Change the autogenerated stub
        }
    }
}